server:
  port: 8000
  
spring: 
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.159:3306/sharingdb?useSSL=false&serverTimezone=Asia/Seoul
    username: 1234
    password: 1234
    
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml
  mapper-locations: classpath*:sqlmap/mappers/**/*.xml
  type-aliases-package: com.shareddiary